import { useState } from "react";
import { formatMoney } from "../rateCard/cards";
import { calculateRegionalQuote, type RegionalQuoteInput } from "../rateCard/regionalTransportQuote";
import type { RateCardDetail, RegionalAdjustment, RegionalFare, RegionalTransportTariff, TransportCharge } from "../rateCard/types";
import "./RegionalTransportWorkbook.css";

type FareNumber = "amount" | "includedKm" | "includedHours" | "extraKm" | "extraHour" | "minKmPerDay" | "minDays" | "driverAllowancePerDay" | "additionalGarageKm" | "additionalReturnKm" | "includedWaitingMinutes" | "waitingRatePerHour" | "timeIncrementMinutes" | "includedStops" | "extraStop" | "includedDays" | "dutyHoursPerDay" | "extraDayRate";
const labels: Record<RegionalFare["service"], string> = {
  "one-way": "Fixed transfer", local: "Local package", outstation: "Outstation per km", daily: "Daily hire", "whole-trip": "Whole-trip package",
};
const amount = (value: number | null | undefined, currency: string) => value == null ? "—" : formatMoney(value, currency);
const num = (value: string) => value === "" ? null : Number(value);
const dateText = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`));

function Section({ title, note, action, enabled = true, children }: { title: string; note?: string; action?: React.ReactNode; enabled?: boolean; children: React.ReactNode }) {
  if (!enabled) return null;
  return <section className="rtw-section"><div className="rtw-section__head"><div><h2>{title}</h2>{note ? <p>{note}</p> : null}</div>{action}</div>{children}</section>;
}

function TaxConfigurationSection({ card, tariff, fares, editing, onChange, onFare, onCharge }: { card: RateCardDetail; tariff: RegionalTransportTariff; fares: RegionalFare[]; editing: boolean; onChange: (patch: Partial<RegionalTransportTariff>) => void; onFare: (id: string, patch: Partial<RegionalFare>) => void; onCharge: (id: string, patch: Partial<TransportCharge>) => void }) {
  const profiles = tariff.taxProfiles || [];
  const addProfile = () => onChange({ taxProfiles: [...profiles, { id: `tax-${Date.now()}`, name: "New tax profile", rate: 0, approved: false }] });
  const updateProfile = (id: string, patch: Partial<(typeof profiles)[number]>) => onChange({ taxProfiles: profiles.map((profile) => profile.id === id ? { ...profile, ...patch } : profile) });
  const profileName = (id?: string) => profiles.find((profile) => profile.id === id)?.name || "Select approved profile";
  const selectProfile = (value: string, onValue: (value: string) => void, label: string) => editing ? <select className="rtw-input" aria-label={label} value={value} onChange={(event) => onValue(event.target.value)}><option value="">Select profile</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name}{profile.approved ? "" : " · pending"}</option>)}</select> : profileName(value);
  return <Section title="Tax configuration" note="Supplier tax is separate from included driver, fuel and tolls. Agency markup is set in Proposal." action={editing ? <button type="button" className="rtw-button" onClick={addProfile}>Add tax profile</button> : null}>
    <div className="rtw-tax-profiles">{profiles.map((profile) => <div key={profile.id}><strong>{editing ? <input className="rtw-input" aria-label={`${profile.name} profile name`} value={profile.name} onChange={(event) => updateProfile(profile.id, { name: event.target.value })} /> : profile.name}</strong><label>Tax rate % {editing ? <input className="rtw-input rtw-input--number" type="number" min="0" max="100" step="0.01" value={profile.rate} onChange={(event) => updateProfile(profile.id, { rate: Number(event.target.value) || 0 })} /> : `${profile.rate}%`}</label><label>{editing ? <input type="checkbox" checked={profile.approved} onChange={(event) => updateProfile(profile.id, { approved: event.target.checked })} /> : null}{profile.approved ? "Approved" : "Pending approval"}</label></div>)}</div>
    <div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Fare method</th><th>Entered amount</th><th>Pricing unit</th><th>Tax presentation</th><th>Tax profile</th></tr></thead><tbody>{fares.map((fare) => <tr key={fare.id}><th scope="row">{labels[fare.service]} · {tariff.vehicles.find((vehicle) => vehicle.id === fare.vehicleId)?.label}<small>{fare.label}</small></th><td>{amount(fare.amount, card.currency)}</td><td>{fare.basis === "per-km" ? "Vehicle-kilometre" : fare.basis === "per-day" ? "Vehicle-day" : fare.basis === "whole-trip" ? "Vehicle-hire" : fare.basis === "fixed" ? "Vehicle-transfer" : "Vehicle-package"}</td><td>{editing ? <select className="rtw-input" value={fare.taxPresentation || "additional"} onChange={(event) => onFare(fare.id, { taxPresentation: event.target.value as RegionalFare["taxPresentation"] })}><option value="additional">Exclusive</option><option value="included">Inclusive</option></select> : fare.taxPresentation === "included" ? "Inclusive" : "Exclusive"}</td><td>{selectProfile(fare.taxProfileId || "", (value) => onFare(fare.id, { taxProfileId: value }), `${fare.label} tax profile`)}</td></tr>)}</tbody></table></div>
    <div className="rtw-table-foot">Tax treatment of additional charges</div><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Charge</th><th>Amount</th><th>Presentation</th><th>Tax profile</th></tr></thead><tbody>{tariff.charges.filter((charge) => charge.treatment === "fixed").map((charge) => <tr key={charge.id}><th scope="row">{charge.label}</th><td>{amount(charge.amount, card.currency)}</td><td>{editing ? <select className="rtw-input" value={charge.taxPresentation || "additional"} onChange={(event) => onCharge(charge.id, { taxPresentation: event.target.value as TransportCharge["taxPresentation"] })}><option value="additional">Exclusive</option><option value="included">Inclusive</option></select> : charge.taxPresentation === "included" ? "Inclusive" : "Exclusive"}</td><td>{selectProfile(charge.taxProfileId || "", (value) => onCharge(charge.id, { taxProfileId: value }), `${charge.label} tax profile`)}</td></tr>)}</tbody></table></div>
  </Section>;
}

function SpecialRulesSection({ card, tariff, editing, onChange }: { card: RateCardDetail; tariff: RegionalTransportTariff; editing: boolean; onChange: (patch: Partial<RegionalTransportTariff>) => void }) {
  const rules = tariff.adjustments || [];
  const update = (id: string, patch: Partial<RegionalAdjustment>) => onChange({ adjustments: rules.map((rule) => rule.id === id ? { ...rule, ...patch } : rule) });
  const add = () => onChange({ adjustments: [...rules, { id: `rule-${Date.now()}`, name: "New date rule", trigger: "dates", dates: [], fareIds: [], methods: ["one-way"], seasonIds: [tariff.seasons[0]?.id || ""], amount: 0, treatment: "additional", stacking: "replace" }] });
  const scope = (rule: RegionalAdjustment) => rule.fareIds.length === 1 ? `fare:${rule.fareIds[0]}` : rule.methods?.length === 1 ? `method:${rule.methods[0]}` : "all";
  return <Section title="Special-date rules" note="Rules are scoped to a season and fare. A replacement supplement does not stack with another adjustment." action={editing ? <button type="button" className="rtw-button" onClick={add}>Add rule</button> : null}><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Rule</th><th>Applies to</th><th>Season</th><th>Trigger</th><th>Dates</th><th>Adjustment</th><th>Combination</th></tr></thead><tbody>{rules.map((rule) => <tr key={rule.id}>
    <th scope="row">{editing ? <input className="rtw-input" value={rule.name} onChange={(event) => update(rule.id, { name: event.target.value })} /> : rule.name}</th>
    <td>{editing ? <select className="rtw-input" value={scope(rule)} onChange={(event) => { const value = event.target.value; update(rule.id, { methods: value.startsWith("method:") ? [value.slice(7) as RegionalFare["service"]] : [], fareIds: value.startsWith("fare:") ? [value.slice(5)] : [] }); }}><option value="all">All fares</option>{(Object.keys(labels) as RegionalFare["service"][]).map((method) => <option key={method} value={`method:${method}`}>All {labels[method].toLowerCase()}</option>)}{tariff.fares.map((fare) => <option key={fare.id} value={`fare:${fare.id}`}>{labels[fare.service]} · {fare.label} · {tariff.vehicles.find((vehicle) => vehicle.id === fare.vehicleId)?.label}</option>)}</select> : rule.fareIds.length === 1 ? tariff.fares.find((fare) => fare.id === rule.fareIds[0])?.label || "Selected fare" : rule.methods?.map((method) => labels[method]).join(", ") || "All fares"}</td>
    <td>{editing ? <select className="rtw-input" value={rule.seasonIds?.[0] || ""} onChange={(event) => update(rule.id, { seasonIds: event.target.value ? [event.target.value] : [] })}><option value="">All seasons</option>{tariff.seasons.map((season) => <option key={season.id} value={season.id}>{season.name}</option>)}</select> : rule.seasonIds?.length ? rule.seasonIds.map((id) => tariff.seasons.find((season) => season.id === id)?.name || id).join(", ") : "All seasons"}</td>
    <td>{editing ? <select className="rtw-input" value={rule.trigger} onChange={(event) => update(rule.id, { trigger: event.target.value as RegionalAdjustment["trigger"] })}><option value="weekend">Weekend</option><option value="dates">Selected dates</option></select> : rule.trigger === "weekend" ? "Saturday / Sunday" : "Selected dates"}</td>
    <td>{rule.trigger === "dates" ? editing ? <input className="rtw-input" aria-label={`${rule.name} dates`} placeholder="YYYY-MM-DD, YYYY-MM-DD" value={rule.dates.join(", ")} onChange={(event) => update(rule.id, { dates: event.target.value.split(",").map((part) => part.trim()).filter(Boolean) })} /> : rule.dates.join(", ") : "Every weekend"}</td>
    <td>{editing ? <div className="rtw-rule-value"><select className="rtw-input" value={rule.treatment} onChange={(event) => update(rule.id, { treatment: event.target.value as RegionalAdjustment["treatment"] })}><option value="additional">Additional</option><option value="unavailable">Unavailable</option></select>{rule.treatment === "additional" ? <input className="rtw-input rtw-input--number" type="number" min="0" aria-label={`${rule.name} amount`} value={rule.amount} onChange={(event) => update(rule.id, { amount: Number(event.target.value) || 0 })} /> : null}</div> : rule.treatment === "unavailable" ? "Unavailable" : amount(rule.amount, card.currency)}</td>
    <td>{editing ? <select className="rtw-input" value={rule.stacking} onChange={(event) => update(rule.id, { stacking: event.target.value as RegionalAdjustment["stacking"] })}><option value="replace">Replace</option><option value="combine">Combine</option></select> : rule.stacking === "replace" ? "Replaces" : "Combines"}</td>
  </tr>)}</tbody></table></div></Section>;
}

function AdditionalChargesSection({ card, tariff, editing, onChange }: { card: RateCardDetail; tariff: RegionalTransportTariff; editing: boolean; onChange: (patch: Partial<RegionalTransportTariff>) => void }) {
  const routes = tariff.routes || [];
  const update = (id: string, patch: Partial<TransportCharge>) => onChange({ charges: tariff.charges.map((charge) => charge.id === id ? { ...charge, ...patch } : charge) });
  const add = () => onChange({ charges: [...tariff.charges, { id: `charge-${Date.now()}`, label: "New charge", treatment: "unconfirmed", amount: null, unit: "vehicle", paidBy: "unconfirmed", collectedBy: "unconfirmed", note: "", routeIds: [], vehicleIds: [], fareIds: [], trigger: "always", taxPresentation: "additional" }] });
  const remove = (id: string) => onChange({ charges: tariff.charges.filter((charge) => charge.id !== id) });
  return <Section title="Additional charges" note="Each charge has a saved scope, trigger, unit and payment responsibility. Unknown mandatory amounts block a quote." action={editing ? <button type="button" className="rtw-button" onClick={add}>Add charge</button> : null}><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Charge</th><th>Route</th><th>Vehicle</th><th>Fare</th><th>Treatment</th><th>Amount</th><th>Charged per</th><th>Trigger</th><th>Payment</th><th>Collected by</th>{editing ? <th>Action</th> : null}</tr></thead><tbody>{tariff.charges.map((charge) => <tr key={charge.id}>
    <th scope="row">{editing ? <input className="rtw-input" aria-label={`${charge.label} charge name`} value={charge.label} onChange={(event) => update(charge.id, { label: event.target.value })} /> : charge.label}</th>
    <td>{editing ? <select className="rtw-input" aria-label={`${charge.label} route`} value={charge.routeIds?.[0] || ""} onChange={(event) => update(charge.id, { routeIds: event.target.value ? [event.target.value] : [] })}><option value="">All routes</option>{routes.map((route) => <option key={route.id} value={route.id}>{route.name}</option>)}</select> : charge.routeIds?.length ? charge.routeIds.map((id) => routes.find((route) => route.id === id)?.name || id).join(", ") : "All routes"}</td>
    <td>{editing ? <select className="rtw-input" aria-label={`${charge.label} vehicle`} value={charge.vehicleIds?.[0] || ""} onChange={(event) => update(charge.id, { vehicleIds: event.target.value ? [event.target.value] : [] })}><option value="">All vehicles</option>{tariff.vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.label}</option>)}</select> : charge.vehicleIds?.length ? charge.vehicleIds.map((id) => tariff.vehicles.find((vehicle) => vehicle.id === id)?.label || id).join(", ") : "All vehicles"}</td>
    <td>{editing ? <select className="rtw-input" aria-label={`${charge.label} fare`} value={charge.fareIds?.[0] || ""} onChange={(event) => update(charge.id, { fareIds: event.target.value ? [event.target.value] : [] })}><option value="">All fares</option>{tariff.fares.map((fare) => <option key={fare.id} value={fare.id}>{labels[fare.service]} · {fare.label} · {fare.vehicleId}</option>)}</select> : charge.fareIds?.length ? charge.fareIds.map((id) => tariff.fares.find((fare) => fare.id === id)?.label || id).join(", ") : "All fares"}</td>
    <td>{editing ? <select className="rtw-input" value={charge.treatment} onChange={(event) => update(charge.id, { treatment: event.target.value as TransportCharge["treatment"] })}><option value="included">Included</option><option value="fixed">Fixed additional</option><option value="actuals">Actuals</option><option value="not-applicable">Not applicable</option><option value="unconfirmed">Unconfirmed</option></select> : charge.treatment === "fixed" ? "Fixed additional" : charge.treatment}</td>
    <td>{editing ? <input className="rtw-input rtw-input--number" type="number" min="0" aria-label={`${charge.label} amount`} disabled={charge.treatment !== "fixed"} value={charge.amount ?? ""} onChange={(event) => update(charge.id, { amount: num(event.target.value) })} /> : amount(charge.amount, card.currency)}</td>
    <td>{editing ? <select className="rtw-input" value={charge.unit} onChange={(event) => update(charge.id, { unit: event.target.value as TransportCharge["unit"] })}><option value="vehicle">Vehicle</option><option value="day">Vehicle / day</option><option value="pickup">Vehicle / pickup</option><option value="transfer">Transfer</option><option value="hire">Hire</option><option value="hour">Vehicle / hour</option></select> : charge.unit}</td>
    <td>{editing ? <div className="rtw-trigger"><select className="rtw-input" aria-label={`${charge.label} trigger`} value={charge.trigger || "always"} onChange={(event) => update(charge.id, { trigger: event.target.value as TransportCharge["trigger"] })}><option value="always">Always</option><option value="night-pickup">Night pickup</option></select>{charge.trigger === "night-pickup" ? <><input className="rtw-input" type="time" aria-label={`${charge.label} night begins`} value={charge.triggerStart || "22:00"} onChange={(event) => update(charge.id, { triggerStart: event.target.value })} /><input className="rtw-input" type="time" aria-label={`${charge.label} night ends`} value={charge.triggerEnd || "06:00"} onChange={(event) => update(charge.id, { triggerEnd: event.target.value })} /></> : null}</div> : charge.trigger === "night-pickup" ? `${charge.triggerStart}–${charge.triggerEnd} ${tariff.timezone}` : "Always"}</td>
    <td>{editing ? <select className="rtw-input" value={charge.paidBy} onChange={(event) => update(charge.id, { paidBy: event.target.value as TransportCharge["paidBy"] })}><option value="agency">Agency pays vendor</option><option value="customer">Customer pays directly</option><option value="unconfirmed">Unconfirmed</option></select> : charge.paidBy === "agency" ? "Agency pays vendor" : charge.paidBy === "customer" ? "Customer pays directly" : "Unconfirmed"}</td>
    <td>{editing ? <select className="rtw-input" value={charge.collectedBy} onChange={(event) => update(charge.id, { collectedBy: event.target.value as TransportCharge["collectedBy"] })}><option value="supplier">Vendor</option><option value="agency">Agency</option><option value="driver">Driver</option><option value="unconfirmed">Unconfirmed</option></select> : charge.collectedBy}</td>
    {editing ? <td><button type="button" className="rtw-button" aria-label={`Remove ${charge.label}`} onClick={() => remove(charge.id)}>Remove</button></td> : null}
  </tr>)}</tbody></table></div></Section>;
}

function WholeTripSection({ card, tariff, fares, editing, onChange }: { card: RateCardDetail; tariff: RegionalTransportTariff; fares: RegionalFare[]; editing: boolean; onChange: (patch: Partial<RegionalTransportTariff>) => void }) {
  const routes = tariff.routes || [];
  const update = (id: string, patch: Partial<RegionalFare>) => onChange({ fares: tariff.fares.map((fare) => fare.id === id ? { ...fare, ...patch } : fare) });
  const add = () => {
    const id = `whole-${Date.now()}`;
    onChange({ fares: [...tariff.fares, ...tariff.seasons.map((season) => ({ id: `${id}-${season.id}`, service: "whole-trip" as const, label: "New whole-trip package", basis: "whole-trip" as const, vehicleId: tariff.vehicles[0]?.id || "", seasonId: season.id, routeId: routes[0]?.id || "", amount: null, includedDays: 1, includedKm: 0, dutyHoursPerDay: 0, extraKm: null, extraHour: null, extraDayRate: null, routeScope: "Saved itinerary", taxPresentation: "additional" as const }))] });
  };
  const moneyField = (fare: RegionalFare, key: "amount" | "extraKm" | "extraHour" | "extraDayRate") => editing ? <input className="rtw-input rtw-input--number" aria-label={`${fare.label} ${key}`} type="number" min="0" value={fare[key] ?? ""} onChange={(event) => update(fare.id, { [key]: num(event.target.value) })} /> : <span className="rtw-money">{amount(fare[key], card.currency)}</span>;
  const countField = (fare: RegionalFare, key: "includedDays" | "includedKm" | "dutyHoursPerDay") => editing ? <input className="rtw-input rtw-input--number" aria-label={`${fare.label} ${key}`} type="number" min="0" value={fare[key] ?? ""} onChange={(event) => update(fare.id, { [key]: num(event.target.value) })} /> : fare[key] ?? "—";
  return <Section title="Whole-trip packages" note="A named itinerary has one whole-hire price. Additional days use the saved extension rate." action={editing ? <button type="button" className="rtw-button" onClick={add}>Add package</button> : null}><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Package</th><th>Saved route</th><th>Vehicle</th><th>Whole-hire price</th><th>Days</th><th>Included km</th><th>Duty h / day</th><th>Extra / km</th><th>Extra / hour</th><th>Extra / day</th>{editing ? <th>Action</th> : null}</tr></thead><tbody>{fares.filter((fare) => fare.service === "whole-trip").map((fare) => <tr key={fare.id}><th scope="row">{editing ? <input className="rtw-input" aria-label={`${fare.label} package name`} value={fare.label} onChange={(event) => update(fare.id, { label: event.target.value })} /> : fare.label}</th><td>{editing ? <select className="rtw-input" value={fare.routeId || ""} onChange={(event) => update(fare.id, { routeId: event.target.value })}><option value="">Select route</option>{routes.map((route) => <option key={route.id} value={route.id}>{route.name}</option>)}</select> : routes.find((route) => route.id === fare.routeId)?.name || "Select route"}</td><td>{editing ? <select className="rtw-input" value={fare.vehicleId} onChange={(event) => update(fare.id, { vehicleId: event.target.value })}>{tariff.vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.label}</option>)}</select> : tariff.vehicles.find((vehicle) => vehicle.id === fare.vehicleId)?.label}</td><td>{moneyField(fare, "amount")}</td><td>{countField(fare, "includedDays")}</td><td>{countField(fare, "includedKm")}</td><td>{countField(fare, "dutyHoursPerDay")}</td><td>{moneyField(fare, "extraKm")}</td><td>{moneyField(fare, "extraHour")}</td><td>{moneyField(fare, "extraDayRate")}</td>{editing ? <td><button type="button" className="rtw-button" onClick={() => onChange({ fares: tariff.fares.filter((item) => item.id !== fare.id) })}>Remove</button></td> : null}</tr>)}</tbody></table></div></Section>;
}

function LocalPackageSection({ tariff, packages, editing, addPackage, removePackage, updatePackage, toggleExcess, findFare, field }: { tariff: RegionalTransportTariff; packages: NonNullable<RegionalTransportTariff["localPackages"]>; editing: boolean; addPackage: () => void; removePackage: (id: string) => void; updatePackage: (id: string, key: "name" | "hours" | "km", value: string) => void; toggleExcess: (id: string, shared: boolean) => void; findFare: (vehicleId: string, packageId: string) => RegionalFare | undefined; field: (fare: RegionalFare | undefined, key: FareNumber, money?: boolean) => React.ReactNode }) {
  const sharedPackage = packages.find((pkg) => pkg.sharedExcess !== false);
  const overrides = packages.filter((pkg) => pkg.sharedExcess === false);
  return <Section title="Local package prices" note="Per-vehicle package prices. Driver and fuel are included; saved excess rates price usage above the package limits." action={editing ? <button type="button" className="rtw-button" onClick={addPackage}>Add package</button> : null}>
    <div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Vehicle</th>{packages.map((pkg) => <th key={pkg.id}>{editing ? <div className="rtw-package-head"><input className="rtw-input" aria-label={`${pkg.name} name`} value={pkg.name} onChange={(event) => updatePackage(pkg.id, "name", event.target.value)} /><label>Hours<input className="rtw-input rtw-input--number" type="number" min="0" value={pkg.hours} onChange={(event) => updatePackage(pkg.id, "hours", event.target.value)} /></label><label>Km<input className="rtw-input rtw-input--number" type="number" min="0" value={pkg.km} onChange={(event) => updatePackage(pkg.id, "km", event.target.value)} /></label><label className="rtw-package-head__override"><input type="checkbox" checked={pkg.sharedExcess === false} onChange={(event) => toggleExcess(pkg.id, !event.target.checked)} /> Own excess rates</label><button type="button" className="rtw-button rtw-package-head__remove" onClick={() => removePackage(pkg.id)}>Remove package</button></div> : <>{pkg.name}<small>Included {pkg.hours} h / {pkg.km} km</small>{pkg.sharedExcess === false ? <small>Own excess rates below</small> : null}</>}</th>)}{sharedPackage ? <><th>Shared extra / km</th><th>Shared extra / hour</th></> : null}</tr></thead><tbody>{tariff.vehicles.map((vehicle) => { const sharedFare = sharedPackage ? findFare(vehicle.id, sharedPackage.id) : undefined; return <tr key={vehicle.id}><th scope="row">{vehicle.label}</th>{packages.map((pkg) => <td key={pkg.id}>{field(findFare(vehicle.id, pkg.id), "amount", true)}</td>)}{sharedPackage ? <><td>{field(sharedFare, "extraKm", true)}</td><td>{field(sharedFare, "extraHour", true)}</td></> : null}</tr>; })}</tbody></table></div>
    {overrides.length ? <><div className="rtw-table-foot">Package-specific excess rates</div><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Package</th><th>Vehicle</th><th>Extra / km</th><th>Extra / hour</th></tr></thead><tbody>{overrides.flatMap((pkg) => tariff.vehicles.map((vehicle) => { const fare = findFare(vehicle.id, pkg.id); return <tr key={`${pkg.id}-${vehicle.id}`}><th scope="row">{pkg.name}</th><td>{vehicle.label}</td><td>{field(fare, "extraKm", true)}</td><td>{field(fare, "extraHour", true)}</td></tr>; }))}</tbody></table></div></> : null}
  </Section>;
}

export function RegionalTransportRates({ card, editing = false, onChange }: { card: RateCardDetail; editing?: boolean; onChange?: (next: RegionalTransportTariff) => void }) {
  const tariff = card.regionalTransport;
  const [seasonId, setSeasonId] = useState(tariff?.seasons[0]?.id || "");
  if (!tariff) return null;
  const season = tariff.seasons.find((item) => item.id === seasonId) || tariff.seasons[0];
  const fares = tariff.fares.filter((fare) => fare.seasonId === season?.id);
  const routes = tariff.routes || [];
  const packages = tariff.localPackages || [];
  const enabledMethods = tariff.enabledMethods || [...new Set(tariff.fares.map((fare) => fare.service))];
  const activeAreaIds = tariff.activeAreaIds || tariff.operatingAreas?.map((area) => area.id) || [];
  const change = (patch: Partial<RegionalTransportTariff>) => onChange?.({ ...tariff, ...patch });
  const changeFare = (id: string, patch: Partial<RegionalFare>) => change({ fares: tariff.fares.map((fare) => fare.id === id ? { ...fare, ...patch } : fare) });
  const changeCharge = (id: string, patch: Partial<TransportCharge>) => change({ charges: tariff.charges.map((charge) => charge.id === id ? { ...charge, ...patch } : charge) });
  const findFare = (service: RegionalFare["service"], vehicleId: string, packageId?: string, routeId?: string) => fares.find((fare) => fare.service === service && fare.vehicleId === vehicleId && (packageId == null || fare.packageId === packageId) && (routeId == null || fare.routeId === routeId));
  const field = (fare: RegionalFare | undefined, key: FareNumber, money = false) => editing && fare ? <input className="rtw-input rtw-input--number" type="number" min="0" aria-label={`${fare.label} ${fare.vehicleId} ${key}`} value={fare[key] ?? ""} onChange={(event) => {
    const value = num(event.target.value);
    if (fare.service === "local" && (key === "extraKm" || key === "extraHour") && (packages.find((pkg) => pkg.id === fare.packageId)?.sharedExcess ?? true)) change({ fares: tariff.fares.map((item) => item.service === "local" && item.seasonId === fare.seasonId && item.vehicleId === fare.vehicleId && (packages.find((pkg) => pkg.id === item.packageId)?.sharedExcess ?? true) ? { ...item, [key]: value } : item) });
    else changeFare(fare.id, { [key]: value });
  }} /> : <span className={money ? "rtw-money" : ""}>{money ? amount(fare?.[key], card.currency) : fare?.[key] ?? "—"}</span>;
  const choice = <T extends string>(fare: RegionalFare, key: keyof RegionalFare, options: { value: T; label: string }[], fallback: T) => editing ? <select className="rtw-input" aria-label={`${fare.label} ${key}`} value={(fare[key] as T | undefined) || fallback} onChange={(event) => changeFare(fare.id, { [key]: event.target.value })}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <span>{options.find((option) => option.value === ((fare[key] as T | undefined) || fallback))?.label}</span>;
  const addSeason = () => {
    const id = `season-${Date.now()}`;
    const startDate = new Date(`${season?.end || "2026-03-31"}T00:00:00Z`);
    startDate.setUTCDate(startDate.getUTCDate() + 1);
    const endDate = new Date(startDate);
    endDate.setUTCDate(endDate.getUTCDate() + 89);
    const next = { id, name: "New season", start: startDate.toISOString().slice(0, 10), end: endDate.toISOString().slice(0, 10) };
    change({ seasons: [...tariff.seasons, next], fares: [...tariff.fares, ...fares.map((fare) => ({ ...fare, id: `${fare.id}-${id}`, seasonId: id, amount: null }))] });
    setSeasonId(id);
  };
  const addPackage = () => {
    const id = `package-${Date.now()}`;
    const pkg = { id, name: "New local package", hours: 8, km: 80, sharedExcess: true };
    change({ localPackages: [...packages, pkg], fares: [...tariff.fares, ...tariff.seasons.flatMap((savedSeason) => tariff.vehicles.map((vehicle) => ({ id: `local-${id}-${vehicle.id}-${savedSeason.id}`, service: "local" as const, label: pkg.name, basis: "hours-km" as const, vehicleId: vehicle.id, seasonId: savedSeason.id, packageId: id, amount: null, includedHours: pkg.hours, includedKm: pkg.km, extraKm: tariff.fares.find((fare) => fare.service === "local" && fare.seasonId === savedSeason.id && fare.vehicleId === vehicle.id)?.extraKm ?? null, extraHour: tariff.fares.find((fare) => fare.service === "local" && fare.seasonId === savedSeason.id && fare.vehicleId === vehicle.id)?.extraHour ?? null, routeScope: tariff.coverage, taxPresentation: "additional" as const })))] });
  };
  const addVehicle = () => {
    const id = `vehicle-${Date.now()}`;
    const vehicle = { id, label: "New vehicle", passengerSeats: null, luggageBags: null, modelOrEquivalent: "" };
    change({ vehicles: [...tariff.vehicles, vehicle], fares: [...tariff.fares, ...tariff.fares.filter((fare) => fare.service !== "whole-trip" && fare.vehicleId === tariff.vehicles[0]?.id).map((fare) => ({ ...fare, id: `${fare.id}-${id}`, vehicleId: id, amount: null }))] });
  };
  const addRoute = () => {
    const id = `route-${Date.now()}`;
    change({ routes: [...routes, { id, name: "New route", from: "", to: "", areaId: tariff.operatingAreas?.[0]?.id || "" }], fares: [...tariff.fares, ...tariff.seasons.flatMap((savedSeason) => tariff.vehicles.map((vehicle) => ({ id: `transfer-${id}-${vehicle.id}-${savedSeason.id}`, service: "one-way" as const, basis: "fixed" as const, label: "New transfer", vehicleId: vehicle.id, seasonId: savedSeason.id, routeId: id, amount: null, includedKm: 0, includedHours: 0, includedWaitingMinutes: 0, extraKm: null, extraHour: null, waitingRatePerHour: null, timeIncrementMinutes: 15, includedStops: 0, extraStop: null, routeScope: "Defined one-way route" })))] });
  };
  const updateRoute = (id: string, key: "name" | "from" | "to" | "areaId", value: string) => change({ routes: routes.map((route) => route.id === id ? { ...route, [key]: value } : route) });
  const updateVehicle = (id: string, key: "label" | "passengerSeats" | "luggageBags", value: string) => change({ vehicles: tariff.vehicles.map((vehicle) => vehicle.id === id ? { ...vehicle, [key]: key === "label" ? value : num(value) } : vehicle) });
  const updatePackage = (id: string, key: "name" | "hours" | "km", value: string) => change({ localPackages: packages.map((pkg) => pkg.id === id ? { ...pkg, [key]: key === "name" ? value : Number(value) || 0 } : pkg), fares: tariff.fares.map((fare) => fare.packageId === id ? { ...fare, ...(key === "name" ? { label: value } : key === "hours" ? { includedHours: Number(value) || 0 } : { includedKm: Number(value) || 0 }) } : fare) });
  const toggleExcess = (id: string, shared: boolean) => {
    const sourceId = packages.find((pkg) => pkg.id !== id && pkg.sharedExcess !== false)?.id;
    change({ localPackages: packages.map((pkg) => pkg.id === id ? { ...pkg, sharedExcess: shared } : pkg), fares: tariff.fares.map((fare) => {
      if (!shared || fare.packageId !== id || !sourceId) return fare;
      const source = tariff.fares.find((item) => item.packageId === sourceId && item.seasonId === fare.seasonId && item.vehicleId === fare.vehicleId);
      return source ? { ...fare, extraKm: source.extraKm, extraHour: source.extraHour } : fare;
    }) });
  };
  const removeVehicle = (id: string) => change({ vehicles: tariff.vehicles.filter((vehicle) => vehicle.id !== id), fares: tariff.fares.filter((fare) => fare.vehicleId !== id), charges: tariff.charges.map((charge) => ({ ...charge, vehicleIds: charge.vehicleIds?.filter((vehicleId) => vehicleId !== id) })) });
  const removePackage = (id: string) => change({ localPackages: packages.filter((pkg) => pkg.id !== id), fares: tariff.fares.filter((fare) => fare.packageId !== id) });
  const editText = (value: string, onValue: (value: string) => void, label: string) => editing ? <input className="rtw-input" aria-label={label} value={value} onChange={(event) => onValue(event.target.value)} /> : value;
  const seasonAction = editing ? <button type="button" className="rtw-button" onClick={addSeason}>Add season</button> : null;

  return <div className="rtw-workbook">
    <Section title="Rate-card information"><div className="rtw-facts">
      <div><span>Vendor</span><strong>{card.vendor}</strong></div><div><span>Transport service</span><strong>{card.property}</strong></div>
      <div><span>Operating areas</span><strong>{(tariff.operatingAreas || []).filter((area) => activeAreaIds.includes(area.id)).map((area) => area.name).join(", ") || "Select areas"}</strong></div>
      <div><span>Currency / price type</span><strong>{card.currency} · Supplier cost</strong></div>
      <div><span>Source document</span><strong>{tariff.sourceDocument || "No vendor tariff uploaded"}</strong>{editing ? <input aria-label="Choose supplier tariff file" type="file" accept=".pdf,.csv,.xlsx,.xls" onChange={(event) => change({ sourceDocument: event.target.files?.[0]?.name || "No vendor tariff uploaded" })} /> : null}</div>
      <div><span>Source</span><strong>{editText(tariff.source, (value) => change({ source: value }), "Fare source")}</strong></div>
      <div><span>Supplier tariff</span><strong>{editing ? <select className="rtw-input" value={tariff.sourceStatus} onChange={(event) => change({ sourceStatus: event.target.value as RegionalTransportTariff["sourceStatus"] })}><option value="illustrative">Pending confirmation</option><option value="supplier-confirmed">Supplier confirmed</option></select> : tariff.sourceStatus === "supplier-confirmed" ? "Supplier confirmed" : "Pending confirmation"}</strong></div>
      <div><span>Vehicle availability</span><strong>{editing ? <select className="rtw-input" value={tariff.availability} onChange={(event) => change({ availability: event.target.value as RegionalTransportTariff["availability"] })}><option value="not-held">Not held</option><option value="held">Held</option><option value="confirmed">Confirmed</option></select> : tariff.availability === "not-held" ? "Not held" : tariff.availability}</strong></div>
      <div><span>Billing timezone</span><strong>{tariff.timezone}</strong></div>
      <div><span>Distance measurement</span><strong>{editing ? <select className="rtw-input" value={tariff.distanceBasis} onChange={(event) => change({ distanceBasis: event.target.value })}><option value="Customer pickup to final drop">Customer pickup to final drop</option><option value="Garage to garage">Garage to garage</option></select> : tariff.distanceBasis}</strong></div>
      <div><span>Tax presentation</span><strong>{editing ? <select className="rtw-input" value={tariff.taxPresentation} onChange={(event) => { const value = event.target.value as RegionalTransportTariff["taxPresentation"]; change({ taxPresentation: value, fares: tariff.fares.map((fare) => ({ ...fare, taxPresentation: value === "unconfirmed" ? undefined : value })), charges: tariff.charges.map((charge) => ({ ...charge, taxPresentation: value === "unconfirmed" ? undefined : value })) }); }}><option value="additional">Exclusive</option><option value="included">Inclusive</option><option value="unconfirmed">Unconfirmed</option></select> : tariff.taxPresentation === "additional" ? "Exclusive" : tariff.taxPresentation === "included" ? "Inclusive" : "Unconfirmed"}</strong></div>
      <div><span>Base fare unit</span><strong>Private vehicle</strong></div>
    </div>{editing ? <div className="rtw-area-picks"><strong>Service areas</strong>{(tariff.operatingAreas || []).map((area) => <label key={area.id}><input type="checkbox" checked={activeAreaIds.includes(area.id)} onChange={(event) => change({ activeAreaIds: event.target.checked ? [...activeAreaIds, area.id] : activeAreaIds.filter((id) => id !== area.id) })} />{area.name}</label>)}</div> : null}</Section>
    <Section title="Defined routes" note="The calculator uses saved route IDs. The reverse direction is a separate row." action={editing ? <button type="button" className="rtw-button" onClick={addRoute}>Add route</button> : null}><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Route / circuit</th><th>From</th><th>To</th><th>Operating area</th></tr></thead><tbody>{routes.map((route) => <tr key={route.id}><th scope="row">{editText(route.name, (value) => updateRoute(route.id, "name", value), `${route.name} route name`)}</th><td>{editText(route.from, (value) => updateRoute(route.id, "from", value), `${route.name} origin`)}</td><td>{editText(route.to, (value) => updateRoute(route.id, "to", value), `${route.name} destination`)}</td><td>{editing ? <select className="rtw-input" value={route.areaId} onChange={(event) => updateRoute(route.id, "areaId", event.target.value)}>{(tariff.operatingAreas || []).map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select> : tariff.operatingAreas?.find((area) => area.id === route.areaId)?.name || "—"}</td></tr>)}</tbody></table></div></Section>
    <Section title="Seasons" note="Each season has its own saved prices. The trip date selects the matching season." action={seasonAction}>
      <div className="rtw-season"><label htmlFor="rtw-season-select">Selected season</label><select id="rtw-season-select" className="rtw-input" value={season?.id || ""} onChange={(event) => setSeasonId(event.target.value)}>{tariff.seasons.map((item) => <option key={item.id} value={item.id}>{item.name} · {dateText(item.start)} – {dateText(item.end)}</option>)}</select></div>
      <div className="rtw-methods"><strong>Fare methods offered</strong>{(Object.keys(labels) as RegionalFare["service"][]).map((method) => editing ? <label key={method}><input type="checkbox" checked={enabledMethods.includes(method)} onChange={(event) => change({ enabledMethods: event.target.checked ? [...enabledMethods, method] : enabledMethods.filter((item) => item !== method) })} />{labels[method]}</label> : enabledMethods.includes(method) ? <span key={method}>{labels[method]}</span> : null)}</div>
      {editing && season ? <div className="rtw-season rtw-season--edit"><label>Name<input className="rtw-input" value={season.name} onChange={(event) => change({ seasons: tariff.seasons.map((item) => item.id === season.id ? { ...item, name: event.target.value } : item) })} /></label><label>Valid from<input className="rtw-input" type="date" value={season.start} onChange={(event) => change({ seasons: tariff.seasons.map((item) => item.id === season.id ? { ...item, start: event.target.value } : item) })} /></label><label>Valid until<input className="rtw-input" type="date" value={season.end} onChange={(event) => change({ seasons: tariff.seasons.map((item) => item.id === season.id ? { ...item, end: event.target.value } : item) })} /></label></div> : null}
    </Section>
    <Section title="Vehicle capacities" note="Passenger seats exclude the driver. Travellers and bags come from the proposal." action={editing ? <button type="button" className="rtw-button" onClick={addVehicle}>Add vehicle</button> : null}><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Vehicle offering</th><th>Passenger seats</th><th>Medium bags</th>{editing ? <th>Action</th> : null}</tr></thead><tbody>{tariff.vehicles.map((vehicle) => <tr key={vehicle.id}><th scope="row">{editText(vehicle.label, (value) => updateVehicle(vehicle.id, "label", value), `${vehicle.label} name`)}</th><td>{editing ? <input className="rtw-input rtw-input--number" type="number" min="0" aria-label={`${vehicle.label} passenger seats`} value={vehicle.passengerSeats ?? ""} onChange={(event) => updateVehicle(vehicle.id, "passengerSeats", event.target.value)} /> : vehicle.passengerSeats ?? "—"}</td><td>{editing ? <input className="rtw-input rtw-input--number" type="number" min="0" aria-label={`${vehicle.label} bag allowance`} value={vehicle.luggageBags ?? ""} onChange={(event) => updateVehicle(vehicle.id, "luggageBags", event.target.value)} /> : vehicle.luggageBags ?? "—"}</td>{editing ? <td><button type="button" className="rtw-button" onClick={() => removeVehicle(vehicle.id)}>Remove</button></td> : null}</tr>)}</tbody></table></div></Section>
    {enabledMethods.includes("local") ? <LocalPackageSection tariff={tariff} packages={packages} editing={editing} addPackage={addPackage} removePackage={removePackage} updatePackage={updatePackage} toggleExcess={toggleExcess} findFare={(vehicleId, packageId) => findFare("local", vehicleId, packageId)} field={field} /> : null}
    <Section enabled={enabledMethods.includes("outstation")} title="Outstation prices" note="One base method per hire: billable km × rate, plus driver allowance and mapped charges."><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Vehicle</th><th>Rate / km</th><th>Minimum km / day</th><th>Minimum days</th><th>Driver / day</th><th>Route / circuit</th><th>Trip type</th><th>Minimum method</th><th>Billable days</th><th>Garage km</th><th>Empty-return km</th><th>Distance rounding</th><th>Cross-season</th></tr></thead><tbody>{tariff.vehicles.map((vehicle) => { const fare = findFare("outstation", vehicle.id); return fare ? <tr key={vehicle.id}><th scope="row">{vehicle.label}</th><td>{field(fare, "amount", true)}</td><td>{field(fare, "minKmPerDay")}</td><td>{field(fare, "minDays")}</td><td>{field(fare, "driverAllowancePerDay", true)}</td><td>{editing ? <select className="rtw-input" aria-label={`${vehicle.label} outstation route`} value={fare.allowedRouteIds?.[0] || ""} onChange={(event) => changeFare(fare.id, { allowedRouteIds: event.target.value ? [event.target.value] : [] })}><option value="">All saved routes</option>{routes.map((route) => <option key={route.id} value={route.id}>{route.name}</option>)}</select> : fare.allowedRouteIds?.length ? fare.allowedRouteIds.map((id) => routes.find((route) => route.id === id)?.name || id).join(", ") : "All saved routes"}</td><td>{choice(fare, "tripType", [{ value: "round-trip", label: "Round trip" }, { value: "one-way", label: "One way" }], "round-trip")}</td><td>{choice(fare, "minimumRule", [{ value: "pooled", label: "Pooled hire" }, { value: "daily", label: "Each day" }, { value: "none", label: "None" }], "pooled")}</td><td>{choice(fare, "billableDayMethod", [{ value: "calendar", label: "Calendar dates" }, { value: "24-hour", label: "24-hour periods" }], "calendar")}</td><td>{field(fare, "additionalGarageKm")}</td><td>{field(fare, "additionalReturnKm")}</td><td>{choice(fare, "distanceRounding", [{ value: "whole-km", label: "Next km" }, { value: "exact", label: "Exact" }], "whole-km")}</td><td>{choice(fare, "crossSeasonPolicy", [{ value: "pickup", label: "Pickup date" }, { value: "split", label: "Split hire" }], "pickup")}</td></tr> : null; })}</tbody></table></div><div className="rtw-table-foot">Distance measured from customer pickup to final drop · {tariff.timezone}</div></Section>
    <Section enabled={enabledMethods.includes("one-way")} title="Fixed-transfer prices" note="Each direction is saved separately. Kilometres check the fixed fare's coverage; they do not multiply the base price." action={editing ? <button type="button" className="rtw-button" onClick={addRoute}>Add route</button> : null}><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Defined route</th><th>Vehicle</th><th>Fixed fare</th><th>Included km</th><th>Included h</th><th>Pickup wait min</th><th>Extra / km</th><th>Extra / h</th><th>Wait / h</th><th>Time increment</th><th>Stops included</th><th>Extra / stop</th></tr></thead><tbody>{routes.filter((route) => fares.some((fare) => fare.service === "one-way" && fare.routeId === route.id) || editing).flatMap((route) => tariff.vehicles.map((vehicle) => { const fare = findFare("one-way", vehicle.id, undefined, route.id); return fare ? <tr key={fare.id}><th scope="row">{editing ? <input className="rtw-input" aria-label={`${route.name} route name`} value={route.name} onChange={(event) => change({ routes: routes.map((item) => item.id === route.id ? { ...item, name: event.target.value } : item) })} /> : route.name}</th><td>{vehicle.label}</td><td>{field(fare, "amount", true)}</td><td>{field(fare, "includedKm")}</td><td>{field(fare, "includedHours")}</td><td>{field(fare, "includedWaitingMinutes")}</td><td>{field(fare, "extraKm", true)}</td><td>{field(fare, "extraHour", true)}</td><td>{field(fare, "waitingRatePerHour", true)}</td><td>{field(fare, "timeIncrementMinutes")}</td><td>{field(fare, "includedStops")}</td><td>{field(fare, "extraStop", true)}</td></tr> : null; }))}</tbody></table></div></Section>
    <Section enabled={enabledMethods.includes("daily")} title="Daily hire prices" note="Unused daily allowances do not carry forward unless the supplier explicitly allows it."><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Vehicle</th><th>Price / day</th><th>Km / day</th><th>Hours / day</th><th>Extra / km</th><th>Extra / hour</th><th>Carry unused allowance</th></tr></thead><tbody>{tariff.vehicles.map((vehicle) => { const fare = findFare("daily", vehicle.id); return fare ? <tr key={fare.id}><th scope="row">{vehicle.label}</th><td>{field(fare, "amount", true)}</td><td>{field(fare, "includedKm")}</td><td>{field(fare, "includedHours")}</td><td>{field(fare, "extraKm", true)}</td><td>{field(fare, "extraHour", true)}</td><td>{editing ? <select className="rtw-input" value={fare.carryUnusedUsage ? "yes" : "no"} onChange={(event) => changeFare(fare.id, { carryUnusedUsage: event.target.value === "yes" })}><option value="no">No</option><option value="yes">Yes</option></select> : fare.carryUnusedUsage ? "Yes" : "No"}</td></tr> : null; })}</tbody></table></div></Section>
    {enabledMethods.includes("whole-trip") ? <WholeTripSection card={card} tariff={tariff} fares={fares} editing={editing} onChange={change} /> : null}
    <AdditionalChargesSection card={card} tariff={tariff} editing={editing} onChange={change} />
    <SpecialRulesSection card={card} tariff={tariff} editing={editing} onChange={change} />
    <TaxConfigurationSection card={card} tariff={tariff} fares={fares.filter((fare) => enabledMethods.includes(fare.service))} editing={editing} onChange={change} onFare={changeFare} onCharge={changeCharge} />
  </div>;
}

const defaultTrip: RegionalQuoteInput = {
  fareId: "outstation-van", date: "2026-10-12", routeId: "kerala-circuit", pickup: "Kochi hotel", drop: "Kochi hotel", pickupTime: "09:00",
  travellers: 10, guideSeats: 1, bags: 10, vehicles: 1, plannedKm: 650, plannedHours: 0, waitingMinutes: 0, additionalStops: 0,
  billableDays: 3, dailyKm: [250, 250, 150], dailyHours: [0, 0, 0],
};

export function RegionalTransportTest({ card }: { card: RateCardDetail }) {
  const tariff = card.regionalTransport;
  const [input, setInput] = useState<RegionalQuoteInput>(() => {
    const offered = tariff?.fares.filter((item) => !tariff.enabledMethods || tariff.enabledMethods.includes(item.service)) || [];
    const selected = offered.find((item) => item.id === defaultTrip.fareId) || offered[0];
    return { ...defaultTrip, fareId: selected?.id || "", routeId: selected?.routeId || (selected?.service === "outstation" ? "kerala-circuit" : "") };
  });
  if (!tariff) return null;
  const fare = tariff.fares.find((item) => item.id === input.fareId);
  const matchingFares = tariff.fares.filter((item) => (!tariff.enabledMethods || tariff.enabledMethods.includes(item.service)) && tariff.seasons.some((season) => season.id === item.seasonId && input.date >= season.start && input.date <= season.end));
  const result = calculateRegionalQuote(tariff, input);
  const routes = tariff.routes || [];
  const set = <K extends keyof RegionalQuoteInput>(key: K, value: RegionalQuoteInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  const numberInput = (label: string, key: "travellers" | "guideSeats" | "bags" | "vehicles" | "plannedKm" | "plannedHours" | "billableDays" | "waitingMinutes" | "additionalStops") => <label><span>{label}</span><input type="number" min="0" value={input[key] ?? 0} onChange={(event) => set(key, Math.max(0, Number(event.target.value) || 0))} /></label>;
  const breakdown = [
    { label: fare?.basis === "per-km" ? `${result.billableKm} billable km × ${amount(fare.amount, card.currency)} × ${input.vehicles} vehicle` : fare?.basis === "per-day" ? `${input.billableDays} days × ${amount(fare.amount, card.currency)} × ${input.vehicles} vehicle` : "Saved base fare × vehicles", value: result.base },
    { label: "Distance and duty excess", value: result.overage },
    { label: "Driver allowance", value: result.driverAllowance },
    { label: "Pickup waiting", value: result.waitingCharge },
    { label: "Additional stops", value: result.stopCharge },
    { label: "Extra hire days", value: result.extensionCharge },
    { label: "Mapped fixed charges", value: result.fixedExtras },
    { label: "Special-date adjustment", value: result.adjustmentCharge },
  ];
  return <div className="rtw-test">
    <section className="rtw-test__inputs"><div className="rtw-test__head"><h2>Test a customer trip</h2><p>Trip inputs come from Proposal. Prices and rules come from the saved supplier card.</p></div>
      <div className="rtw-test__fields"><label className="rtw-test__wide"><span>Saved fare method and vehicle</span><select value={input.fareId} onChange={(event) => { const next = tariff.fares.find((item) => item.id === event.target.value); setInput((current) => ({ ...current, fareId: event.target.value, routeId: next?.routeId || (next?.service === "outstation" ? "kerala-circuit" : ""), billableDays: next?.basis === "hours-km" || next?.basis === "fixed" ? 1 : current.billableDays })); }}>{matchingFares.length === 0 ? <option value="">No saved fare for this date</option> : null}{matchingFares.map((item) => <option key={item.id} value={item.id}>{labels[item.service]} · {tariff.vehicles.find((vehicle) => vehicle.id === item.vehicleId)?.label} · {item.label}{item.routeId ? ` · ${routes.find((route) => route.id === item.routeId)?.name || item.routeId}` : ""}</option>)}</select></label>
        <label><span>Travel starts</span><input type="date" value={input.date} onChange={(event) => { const date = event.target.value; const match = tariff.fares.find((item) => item.service === fare?.service && item.vehicleId === fare.vehicleId && item.packageId === fare.packageId && item.routeId === fare.routeId && tariff.seasons.some((season) => season.id === item.seasonId && date >= season.start && date <= season.end)); setInput((current) => ({ ...current, date, fareId: match?.id || current.fareId })); }} /></label>
        <label><span>Defined route</span><select value={input.routeId || ""} onChange={(event) => set("routeId", event.target.value)}><option value="">Select route or local area</option>{routes.map((route) => <option key={route.id} value={route.id}>{route.name}</option>)}</select></label>
        <label><span>Customer pickup</span><input value={input.pickup} onChange={(event) => set("pickup", event.target.value)} /></label><label><span>Final drop</span><input value={input.drop} onChange={(event) => set("drop", event.target.value)} /></label>
        <label><span>Pickup time</span><input type="time" value={input.pickupTime || ""} onChange={(event) => set("pickupTime", event.target.value)} /></label>
        {numberInput("Customers", "travellers")}{numberInput("Guide seats", "guideSeats")}{numberInput("Medium bags", "bags")}{numberInput("Vehicle quantity", "vehicles")}
        {numberInput("Billable days", "billableDays")}{numberInput("Planned chargeable km", "plannedKm")}{numberInput("Service duty hours", "plannedHours")}
        {fare?.basis === "fixed" ? <>{numberInput("Pickup waiting minutes", "waitingMinutes")}{numberInput("Additional stops", "additionalStops")}</> : null}
        {fare?.minimumRule === "daily" || fare?.basis === "per-day" && !fare.carryUnusedUsage ? <label className="rtw-test__wide"><span>Planned km by day, comma separated</span><input value={input.dailyKm.join(", ")} onChange={(event) => set("dailyKm", event.target.value.split(",").map((part) => Number(part.trim()) || 0))} /></label> : null}
        {fare?.basis === "per-day" && !fare.carryUnusedUsage ? <label className="rtw-test__wide"><span>Duty hours by day, comma separated</span><input value={(input.dailyHours || []).join(", ")} onChange={(event) => set("dailyHours", event.target.value.split(",").map((part) => Number(part.trim()) || 0))} /></label> : null}
      </div>
      <div className="rtw-test__capacity">Minimum vehicles for seats and bags: <strong>{result.minimumVehicles ?? "Confirm capacity"}</strong></div>
    </section>
    <section className="rtw-test__result"><div className="rtw-test__head"><h2>Supplier calculation</h2><p>{fare ? `${labels[fare.service]} · ${result.vehicle?.label || "Vehicle"}` : "Select a saved fare"}</p></div>
      <div className="rtw-test__total"><span>Supplier subtotal before tax</span><strong>{amount(result.knownSubtotal, card.currency)}</strong><small>{result.quoteBasis === "base-plus-actuals" ? "Base price plus actuals" : result.quoteBasis === "needs-review" ? "Review required before quoting" : "Fixed for the selected scope"}</small></div>
      <div className="rtw-test__breakdown">{breakdown.filter((item) => item.value == null || item.value !== 0).map((item) => <div key={item.label}><span>{item.label}</span><strong>{amount(item.value, card.currency)}</strong></div>)}<div><span>Tax from approved profile</span><strong>{result.taxAmount == null ? "Pending profile" : amount(result.taxAmount, card.currency)}</strong></div><div className="rtw-test__payable"><span>Supplier payable</span><strong>{result.supplierPayable == null ? "Pending tax" : amount(result.supplierPayable, card.currency)}</strong></div></div>
      {result.actuals.length ? <p className="rtw-test__actuals"><strong>Base price plus actuals:</strong> {result.actuals.join(", ")}</p> : null}
      {result.directPayments.length ? <p className="rtw-test__actuals"><strong>Customer pays directly:</strong> {result.directPayments.join(", ")}</p> : null}
      <div className="rtw-test__review"><h3>{result.blockers.length ? "Complete before customer quote" : "Rate scope checked"}</h3>{result.blockers.length ? <ul>{result.blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul> : <p>Saved numbers cover this trip. Proposal can apply the selling-price policy separately.</p>}</div>
    </section>
  </div>;
}
